apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-fibonacci-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-fibonacci-app
  template:
    metadata:
      labels:
        app: flask-fibonacci-app
    spec:
      containers:
      - name: flask-fibonacci-app
        image: flask-fibonacci-app
        ports:
        - containerPort: 80
